runtime: nodejs18

instance_class: F1

includes:
  - ./server/env.yaml

handlers:
  # Catch all handler to express app
  - url: .*
    secure: always
    redirect_http_response_code: 301
    script: auto
  # # Serve all static files with url ending with a file extension
  # - url: /.*
  #   static_files: client/build/\1
  #   upload: client/build/(.*\..+)$
  #   secure: always
